import { mkdir, writeFile } from 'node:fs/promises';
import { closeDb } from './client';
import { listDirectoryTeams } from '../directory/users';

async function main(): Promise<void> {
  const teams = await listDirectoryTeams();
  if (teams.length === 0) {
    throw new Error('Cannot export empty company directory. Run npm run db:seed first.');
  }

  await mkdir('src/data/generated', { recursive: true });
  await writeFile(
    'src/data/generated/companyDirectory.ts',
    `// Generated by server/db/exportCompanyDirectory.ts from the users table. Do not edit by hand.
` +
      `export const companyDirectoryTeams = ${JSON.stringify(teams, null, 2)} as const;

` +
      `export const companyDirectorySummary = ${JSON.stringify({
        classification: 'PUBLIC CONTACT ROUTING — USERS TABLE',
        revision: 'SC-DIR-2026.05',
        note: 'Directory rows are generated from the users table. Responses are issued in controlled revisions.',
      }, null, 2)} as const;
`,
  );
  console.log(`exported directory teams=${teams.length}`);
}

main()
  .catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDb();
  });
